import { CovidRequest } from '../models/BL/covid-request';

export const cm = () => {
    let reqs = [];
    let request = new CovidRequest(0);

    request.city = "Dnipro";
    request.zoz = "#1 Region Clinic";
    request.zozAddress = "Dnipro city, Malin st., 54 h.";
    request.registrationDate = new Date();
    request.senderFullName = "Thyhankov Mykyta Dmytrovich";
    request.senderProfession = "Family Doctor ";
    request.requestReason = "Stomachache";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date();
    request.patientFirstName =  "Richard";
    request.patientLastName = "Older";
    request.patientMiddleName = "Jonh";
    request.patientSex = "male";
    request.patientBirthDate = new Date(1990, 1, 1);
    request.patientAge = 31;
    request.patientCity = "New-York";
    request.patientAddress = "Dnipro city, Malin st., 54 h.";
    request.patientPhone = "+75478698547";
    request.additinalInfo = "Has allergy on cats and some plants. ";
    request.isDoctor = false;
    request.doctorProfession = "";
    request.materialType = "Blood";
    request.diagnos = "*** Pills, 2 consultation";

    reqs.push(request);

    request.id = 1;
    request.city = "Dnipro";
    request.zoz = "#1 Region Clinic";
    request.zozAddress = "Dnipro city, Malin st., 54 h.";
    request.registrationDate = new Date();
    request.senderFullName = "Thyhankov Mykyta Dmytrovich";
    request.senderProfession = "Family Doctor ";
    request.requestReason = "Stomachache";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date();
    request.patientFirstName =  "Richard";
    request.patientLastName = "Older";
    request.patientMiddleName = "Jonh";
    request.patientSex = "male";
    request.patientBirthDate = new Date(1990, 1, 1);
    request.patientAge = 31;
    request.patientCity = "New-York";
    request.patientAddress = "Dnipro city, Malin st., 54 h.";
    request.patientPhone = "+75478698547";
    request.additinalInfo = "Has allergy on cats and some plants. ";
    request.isDoctor = false;
    request.doctorProfession = "";
    request.materialType = "Blood";
    request.diagnos = "*** Pills, 2 consultation";

    reqs.push(request);

    request.id = 1;
    request.city = "Dnipro";
    request.zoz = "#1 Region Clinic";
    request.zozAddress = "Dnipro city, Malin st., 54 h.";
    request.registrationDate = new Date();
    request.senderFullName = "Thyhankov Mykyta Dmytrovich";
    request.senderProfession = "Family Doctor ";
    request.requestReason = "Stomachache";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date();
    request.patientFirstName =  "Richard";
    request.patientLastName = "Older";
    request.patientMiddleName = "Jonh";
    request.patientSex = "male";
    request.patientBirthDate = new Date(1990, 1, 1);
    request.patientAge = 31;
    request.patientCity = "New-York";
    request.patientAddress = "Dnipro city, Malin st., 54 h.";
    request.patientPhone = "+75478698547";
    request.additinalInfo = "Has allergy on cats and some plants. ";
    request.isDoctor = false;
    request.doctorProfession = "";
    request.materialType = "Blood";
    request.diagnos = "*** Pills, 2 consultation";

    reqs.push(request);

    request.id = 1;
    request.city = "Dnipro";
    request.zoz = "#1 Region Clinic";
    request.zozAddress = "Dnipro city, Malin st., 54 h.";
    request.registrationDate = new Date();
    request.senderFullName = "Thyhankov Mykyta Dmytrovich";
    request.senderProfession = "Family Doctor ";
    request.requestReason = "Stomachache";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date();
    request.patientFirstName =  "Richard";
    request.patientLastName = "Older";
    request.patientMiddleName = "Jonh";
    request.patientSex = "male";
    request.patientBirthDate = new Date(1990, 1, 1);
    request.patientAge = 31;
    request.patientCity = "New-York";
    request.patientAddress = "Dnipro city, Malin st., 54 h.";
    request.patientPhone = "+75478698547";
    request.additinalInfo = "Has allergy on cats and some plants. ";
    request.isDoctor = false;
    request.doctorProfession = "";
    request.materialType = "Blood";
    request.diagnos = "*** Pills, 2 consultation";

    reqs.push(request);

    request.id = 1;
    request.city = "Dnipro";
    request.zoz = "#1 Region Clinic";
    request.zozAddress = "Dnipro city, Malin st., 54 h.";
    request.registrationDate = new Date();
    request.senderFullName = "Thyhankov Mykyta Dmytrovich";
    request.senderProfession = "Family Doctor ";
    request.requestReason = "Stomachache";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date();
    request.patientFirstName =  "Richard";
    request.patientLastName = "Older";
    request.patientMiddleName = "Jonh";
    request.patientSex = "male";
    request.patientBirthDate = new Date(1990, 1, 1);
    request.patientAge = 31;
    request.patientCity = "New-York";
    request.patientAddress = "Dnipro city, Malin st., 54 h.";
    request.patientPhone = "+75478698547";
    request.additinalInfo = "Has allergy on cats and some plants. ";
    request.isDoctor = false;
    request.doctorProfession = "";
    request.materialType = "Blood";
    request.diagnos = "*** Pills, 2 consultation";

    reqs.push(request);

    request.id = 1;
    request.city = "Dnipro";
    request.zoz = "#1 Region Clinic";
    request.zozAddress = "Dnipro city, Malin st., 54 h.";
    request.registrationDate = new Date();
    request.senderFullName = "Thyhankov Mykyta Dmytrovich";
    request.senderProfession = "Family Doctor ";
    request.requestReason = "Stomachache";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date();
    request.patientFirstName =  "Richard";
    request.patientLastName = "Older";
    request.patientMiddleName = "Jonh";
    request.patientSex = "male";
    request.patientBirthDate = new Date(1990, 1, 1);
    request.patientAge = 31;
    request.patientCity = "New-York";
    request.patientAddress = "Dnipro city, Malin st., 54 h.";
    request.patientPhone = "+75478698547";
    request.additinalInfo = "Has allergy on cats and some plants. ";
    request.isDoctor = false;
    request.doctorProfession = "";
    request.materialType = "Blood";
    request.diagnos = "*** Pills, 2 consultation";

    reqs.push(request);

    request.id = 1;
    request.city = "Dnipro";
    request.zoz = "#1 Region Clinic";
    request.zozAddress = "Dnipro city, Malin st., 54 h.";
    request.registrationDate = new Date();
    request.senderFullName = "Thyhankov Mykyta Dmytrovich";
    request.senderProfession = "Family Doctor ";
    request.requestReason = "Stomachache";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date();
    request.patientFirstName =  "Richard";
    request.patientLastName = "Older";
    request.patientMiddleName = "Jonh";
    request.patientSex = "male";
    request.patientBirthDate = new Date(1990, 1, 1);
    request.patientAge = 31;
    request.patientCity = "New-York";
    request.patientAddress = "Dnipro city, Malin st., 54 h.";
    request.patientPhone = "+75478698547";
    request.additinalInfo = "Has allergy on cats and some plants. ";
    request.isDoctor = false;
    request.doctorProfession = "";
    request.materialType = "Blood";
    request.diagnos = "*** Pills, 2 consultation";

    reqs.push(request);

    request.id = 1;
    request.city = "Dnipro";
    request.zoz = "#1 Region Clinic";
    request.zozAddress = "Dnipro city, Malin st., 54 h.";
    request.registrationDate = new Date();
    request.senderFullName = "Thyhankov Mykyta Dmytrovich";
    request.senderProfession = "Family Doctor ";
    request.requestReason = "Stomachache";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date();
    request.patientFirstName =  "Richard";
    request.patientLastName = "Older";
    request.patientMiddleName = "Jonh";
    request.patientSex = "male";
    request.patientBirthDate = new Date(1990, 1, 1);
    request.patientAge = 31;
    request.patientCity = "New-York";
    request.patientAddress = "Dnipro city, Malin st., 54 h.";
    request.patientPhone = "+75478698547";
    request.additinalInfo = "Has allergy on cats and some plants. ";
    request.isDoctor = false;
    request.doctorProfession = "";
    request.materialType = "Blood";
    request.diagnos = "*** Pills, 2 consultation";

    return reqs;
};
