import { CovidRequest } from '../models/BL/covid-request';

export const cm = () => {
    let reqs = [];
    let request = new CovidRequest(0);

    request.city = "test";
    request.zoz = "test";
    request.zozAddress = "test";
    request.registrationDate = new Date();
    request.senderFullName = "test";
    request.senderProfession = "test";
    request.requestReason = "test";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date();
    request.patientFirstName =  "Teeest";
    request.patientLastName = "Teeest";
    request.patientMiddleName = "test";
    request.patientSex = "test";
    request.patientBirthDate = new Date();
    request.patientAge = 20;
    request.patientCity = "test";
    request.patientAddress = "test";
    request.patientPhone = "test";
    request.additinalInfo = "test";
    request.isDoctor = false;
    request.doctorProfession = "test";
    request.materialType = "test";
    request.diagnos = "test";

    reqs.push(request);

    request.id = 1;
    request.city = "test";
    request.zoz = "test";
    request.zozAddress = "test";
    request.registrationDate = new Date();
    request.senderFullName = "test";
    request.senderProfession = "test";
    request.requestReason = "test";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date;
    request.patientFirstName =  "ASDASDASD";
    request.patientLastName = "asdasdasdasd";
    request.patientMiddleName = "test";
    request.patientSex = "test";
    request.patientBirthDate = new Date();
    request.patientAge = 20;
    request.patientCity = "test";
    request.patientAddress = "test";
    request.patientPhone = "test";
    request.additinalInfo = "test";
    request.isDoctor = false;
    request.doctorProfession = "test";
    request.materialType = "test";
    request.diagnos = "test";

    reqs.push(request);

    request.id = 1;
    request.city = "test";
    request.zoz = "test";
    request.zozAddress = "test";
    request.registrationDate = new Date();
    request.senderFullName = "test";
    request.senderProfession = "test";
    request.requestReason = "test";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date;
    request.patientFirstName =  "ASDASDASD";
    request.patientLastName = "asdasdasdasd";
    request.patientMiddleName = "test";
    request.patientSex = "test";
    request.patientBirthDate = new Date();
    request.patientAge = 20;
    request.patientCity = "test";
    request.patientAddress = "test";
    request.patientPhone = "test";
    request.additinalInfo = "test";
    request.isDoctor = false;
    request.doctorProfession = "test";
    request.materialType = "test";
    request.diagnos = "test";

    reqs.push(request);

    request.id = 1;
    request.city = "test";
    request.zoz = "test";
    request.zozAddress = "test";
    request.registrationDate = new Date();
    request.senderFullName = "test";
    request.senderProfession = "test";
    request.requestReason = "test";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date;
    request.patientFirstName =  "ASDASDASD";
    request.patientLastName = "asdasdasdasd";
    request.patientMiddleName = "test";
    request.patientSex = "test";
    request.patientBirthDate = new Date();
    request.patientAge = 20;
    request.patientCity = "test";
    request.patientAddress = "test";
    request.patientPhone = "test";
    request.additinalInfo = "test";
    request.isDoctor = false;
    request.doctorProfession = "test";
    request.materialType = "test";
    request.diagnos = "test";

    reqs.push(request);

    request.id = 1;
    request.city = "test";
    request.zoz = "test";
    request.zozAddress = "test";
    request.registrationDate = new Date();
    request.senderFullName = "test";
    request.senderProfession = "test";
    request.requestReason = "test";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date;
    request.patientFirstName =  "ASDASDASD";
    request.patientLastName = "asdasdasdasd";
    request.patientMiddleName = "test";
    request.patientSex = "test";
    request.patientBirthDate = new Date();
    request.patientAge = 20;
    request.patientCity = "test";
    request.patientAddress = "test";
    request.patientPhone = "test";
    request.additinalInfo = "test";
    request.isDoctor = false;
    request.doctorProfession = "test";
    request.materialType = "test";
    request.diagnos = "test";

    reqs.push(request);

    request.id = 1;
    request.city = "test";
    request.zoz = "test";
    request.zozAddress = "test";
    request.registrationDate = new Date();
    request.senderFullName = "test";
    request.senderProfession = "test";
    request.requestReason = "test";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date;
    request.patientFirstName =  "ASDASDASD";
    request.patientLastName = "asdasdasdasd";
    request.patientMiddleName = "test";
    request.patientSex = "test";
    request.patientBirthDate = new Date();
    request.patientAge = 20;
    request.patientCity = "test";
    request.patientAddress = "test";
    request.patientPhone = "test";
    request.additinalInfo = "test";
    request.isDoctor = false;
    request.doctorProfession = "test";
    request.materialType = "test";
    request.diagnos = "test";

    reqs.push(request);

    request.id = 1;
    request.city = "test";
    request.zoz = "test";
    request.zozAddress = "test";
    request.registrationDate = new Date();
    request.senderFullName = "test";
    request.senderProfession = "test";
    request.requestReason = "test";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date;
    request.patientFirstName =  "ASDASDASD";
    request.patientLastName = "asdasdasdasd";
    request.patientMiddleName = "test";
    request.patientSex = "test";
    request.patientBirthDate = new Date();
    request.patientAge = 20;
    request.patientCity = "test";
    request.patientAddress = "test";
    request.patientPhone = "test";
    request.additinalInfo = "test";
    request.isDoctor = false;
    request.doctorProfession = "test";
    request.materialType = "test";
    request.diagnos = "test";

    reqs.push(request);

    request.id = 1;
    request.city = "test";
    request.zoz = "test";
    request.zozAddress = "test";
    request.registrationDate = new Date();
    request.senderFullName = "test";
    request.senderProfession = "test";
    request.requestReason = "test";
    request.sickPatientFullName = "test";
    request.sickPatientAddress = "test";
    request.sickPatienDate = new Date;
    request.patientFirstName =  "ASDASDASD";
    request.patientLastName = "asdasdasdasd";
    request.patientMiddleName = "test";
    request.patientSex = "test";
    request.patientBirthDate = new Date();
    request.patientAge = 20;
    request.patientCity = "test";
    request.patientAddress = "test";
    request.patientPhone = "test";
    request.additinalInfo = "test";
    request.isDoctor = false;
    request.doctorProfession = "test";
    request.materialType = "test";
    request.diagnos = "test";

    return reqs;
};
