export const cm = [{ 
    id: 0,
    city: "test",
    zoz: "test",
    zozAddress: "test",
    registrationDate: new Date(),
    senderFullName: "test",
    senderProfession: "test",
    requestReason: "test",
    sickPatientFullName: "test",
    sickPatientAddress: "test",
    sickPatienDate: new Date(),
    patientFirstName:  "Teeest",
    patientLastName: "Teeest",
    patientMiddleName: "test",
    patientSex: "test",
    patientBirthDate: new Date(),
    patientAge: 20,
    patientCity: "test",
    patientAddress: "test",
    patientPhone: "test",
    additinalInfo: "test",
    isDoctor: false,
    doctorProfession: "test",
    materialType: "test",
    diagnos: "test"
},{ 
    id: 1,
    city: "test",
    zoz: "test",
    zozAddress: "test",
    registrationDate: new Date(),
    senderFullName: "test",
    senderProfession: "test",
    requestReason: "test",
    sickPatientFullName: "test",
    sickPatientAddress: "test",
    sickPatienDate: new Date,
    patientFirstName:  "ASDASDASD",
    patientLastName: "asdasdasdasd",
    patientMiddleName: "test",
    patientSex: "test",
    patientBirthDate: new Date(),
    patientAge: 20,
    patientCity: "test",
    patientAddress: "test",
    patientPhone: "test",
    additinalInfo: "test",
    isDoctor: false,
    doctorProfession: "test",
    materialType: "test",
    diagnos: "test"
}]